# Generated by Django 6.0.2 on 2026-02-16 12:39

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
